# -*- coding: utf-8 -*-
"""DTCR_UNet_Phase1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dx-Xf7gSvKolXqAkiroFvObXmt4ZdE5m

Data Collection & Preprocessing

Datasets: **MosMedData** (real, Kaggle: `mathurinache/mosmeddata-chest-ct-scans-with-covid19`) +
**LIDC-IDRI** (pre-sliced nodule-crop version, Kaggle: `shuyueg/lidc-idri-byslices`, subsampled
to ~1000 pairs to roughly balance MosMedData).

Mount Drive & create project folder structure
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import os, json, random
import numpy as np

PROJECT_ROOT = '/content/drive/MyDrive/DTCR_UNet_Project'

folders = [
    'data/raw/mosmeddata',
    'data/raw/lidc_idri',
    'data/raw/covid19_ct_seg',      # phase 2
    'data/raw/cc_ccii',             # phase 2
    'data/processed/train/images',
    'data/processed/train/masks',
    'data/processed/val/images',
    'data/processed/val/masks',
    'data/processed/test/images',
    'data/processed/test/masks',
    'checkpoints',
    'logs',
    'notebooks',
    'src',
]

for f in folders:
    os.makedirs(os.path.join(PROJECT_ROOT, f), exist_ok=True)

print("Project structure ready at:", PROJECT_ROOT)

"""Kaggle API setup (Colab Secrets)


"""

from google.colab import userdata

os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_API_TOKEN')

!pip install -q kaggle
!kaggle --version

"""Central setup: paths, constants, and all helper functions

Everything downstream depends on this cell.
"""

seg_dir = Path(PROJECT_ROOT) / 'data/raw/lidc_idri/seg_LIDC-IDRI'
masks_dir = Path(PROJECT_ROOT) / 'data/raw/mosmeddata/masks'
studies_root = Path(PROJECT_ROOT) / 'data/raw/mosmeddata/studies'
OUT = Path(PROJECT_ROOT) / 'data/processed'

TARGET_SIZE = 512

import cv2
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# ---------- MosMedData helpers ----------
def find_ct_path(study_id):
    for ct_folder in ['CT-0', 'CT-1', 'CT-2', 'CT-3', 'CT-4']:
        candidate = studies_root / ct_folder / f"{study_id}.nii"
        if candidate.exists():
            return candidate
    return None

def normalize_ct_slice(slice_2d, hu_min=-1000, hu_max=400):
    """Clip to a lung-relevant HU window, then scale to [0,1]."""
    clipped = np.clip(slice_2d, hu_min, hu_max)
    normalized = (clipped - hu_min) / (hu_max - hu_min)
    return normalized.astype(np.float32)

def resize_if_needed(img, is_mask):
    if img.shape[0] != TARGET_SIZE or img.shape[1] != TARGET_SIZE:
        interp = cv2.INTER_NEAREST if is_mask else cv2.INTER_LINEAR
        img = cv2.resize(img, (TARGET_SIZE, TARGET_SIZE), interpolation=interp)
    return img

# ---------- LIDC-IDRI helpers ----------
def load_lidc_image(path):
    img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if img is None:
        return None
    if img.ndim == 3:
        img = cv2.cvtColor(img[:, :, :3], cv2.COLOR_BGR2GRAY)
    return img

def load_lidc_mask(path):
    m = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if m is None:
        return None
    if m.ndim == 3:
        m = cv2.cvtColor(m[:, :, :3], cv2.COLOR_BGR2GRAY)
    return m

def resize_lidc(arr, is_mask):
    interp = cv2.INTER_NEAREST if is_mask else cv2.INTER_LINEAR
    return cv2.resize(arr, (TARGET_SIZE, TARGET_SIZE), interpolation=interp)

print("Setup complete.")
print("PROJECT_ROOT exists:", os.path.exists(PROJECT_ROOT))

"""## Cell 4 - Download MosMedData (skips if already present)

Correct source (confirmed to include both `studies/` (1110 volumes, CT-0..CT-4) and `masks/`
(50 files) — an earlier mirror we tried was missing masks entirely, so this specific dataset
slug matters.

"""

mosmed_dir = os.path.join(PROJECT_ROOT, 'data/raw/mosmeddata')

if os.path.exists(os.path.join(mosmed_dir, 'studies')) and os.path.exists(os.path.join(mosmed_dir, 'masks')):
    print("MosMedData already present — skipping download.")
else:
    !kaggle datasets download -d mathurinache/mosmeddata-chest-ct-scans-with-covid19 -p "{mosmed_dir}" --unzip

    # The zip extracts into a long, unwieldy nested folder name -- flatten it.
    messy_folder = os.path.join(
        mosmed_dir,
        'MosMedData Chest CT Scans with COVID-19 Related Findings COVID19_1110 1.0'
    )
    if os.path.exists(messy_folder):
        import shutil
        docs_dir = os.path.join(mosmed_dir, 'docs')
        os.makedirs(docs_dir, exist_ok=True)

        for sub in ['masks', 'studies']:
            src = os.path.join(messy_folder, sub)
            dst = os.path.join(mosmed_dir, sub)
            if os.path.exists(src) and not os.path.exists(dst):
                shutil.move(src, dst)

        # Anything left (README, LICENSE, etc.) -> docs/
        for f in os.listdir(messy_folder):
            shutil.move(os.path.join(messy_folder, f), os.path.join(docs_dir, f))

        if not os.listdir(messy_folder):
            os.rmdir(messy_folder)

print("\nFinal contents of mosmeddata/:", sorted(os.listdir(mosmed_dir)))
print("Studies breakdown:")
for ct in ['CT-0', 'CT-1', 'CT-2', 'CT-3', 'CT-4']:
    p = os.path.join(mosmed_dir, 'studies', ct)
    if os.path.exists(p):
        print(f"  {ct}: {len(os.listdir(p))} files")
print(f"Masks: {len(os.listdir(os.path.join(mosmed_dir, 'masks')))} files")

"""## Cell 5 - Download LIDC-IDRI (skips if already present)"""

lidc_dir = os.path.join(PROJECT_ROOT, 'data/raw/lidc_idri')

if os.path.exists(os.path.join(lidc_dir, 'seg_LIDC-IDRI')):
    print("LIDC-IDRI already present — skipping download.")
else:
    !kaggle datasets download -d shuyueg/lidc-idri-byslices -p "{lidc_dir}" --unzip

print("Total patients:", len(os.listdir(seg_dir)))

"""## Cell 6 — MosMedData: build deduped (study, slice_index) pairs

For every slice containing lesion voxels, keep it plus its immediate neighbors above/below
(local 3-slice context, per the paper's description), deduped so overlapping neighbor windows
aren't double-counted.

"""

import nibabel as nib

mask_files = sorted(masks_dir.glob('*_mask.nii'))
print(f"Total mask files: {len(mask_files)}")

all_pairs = []  # list of (study_id, slice_idx), deduped
missing_ct = []

for mask_file in mask_files:
    study_id = mask_file.stem.replace('_mask', '')
    ct_path = find_ct_path(study_id)
    if ct_path is None:
        missing_ct.append(study_id)
        continue

    mask_vol = nib.load(str(mask_file)).get_fdata()
    lesion_slices = np.where(mask_vol.sum(axis=(0, 1)) > 0)[0]

    slice_idx_set = set()
    for s in lesion_slices:
        for offset in (-1, 0, 1):
            idx = s + offset
            if 0 <= idx < mask_vol.shape[2]:
                slice_idx_set.add(int(idx))

    for idx in slice_idx_set:
        all_pairs.append((study_id, idx))

print(f"Studies missing a matching CT volume: {len(missing_ct)}")
print(f"Total deduped (image, mask) slice pairs: {len(all_pairs)}")

# Study-level split (6:2:2) -- keeps all of one patient's slices in one split, avoids leakage
unique_studies = sorted(set(p[0] for p in all_pairs))
train_studies, temp_studies = train_test_split(unique_studies, test_size=0.4, random_state=42)
val_studies, test_studies = train_test_split(temp_studies, test_size=0.5, random_state=42)

print(f"Study split: {len(train_studies)} train / {len(val_studies)} val / {len(test_studies)} test")

"""## Cell 7 — MosMedData: save train/val/test .npy pairs"""

def save_mosmed_pairs(study_list, split_name):
    img_out = OUT / split_name / 'images'
    mask_out = OUT / split_name / 'masks'
    saved = 0

    studies_in_split = set(study_list)
    pairs_for_split = [(sid, idx) for sid, idx in all_pairs if sid in studies_in_split]
    pairs_by_study = {}
    for sid, idx in pairs_for_split:
        pairs_by_study.setdefault(sid, []).append(idx)

    for study_id, slice_indices in pairs_by_study.items():
        ct_path = find_ct_path(study_id)
        mask_path = masks_dir / f"{study_id}_mask.nii"

        ct_vol = nib.load(str(ct_path)).get_fdata()
        mask_vol = nib.load(str(mask_path)).get_fdata()

        for idx in slice_indices:
            ct_slice = ct_vol[:, :, idx]
            mask_slice = mask_vol[:, :, idx]

            ct_norm = normalize_ct_slice(ct_slice)
            ct_norm = resize_if_needed(ct_norm, is_mask=False)

            mask_bin = (mask_slice > 0).astype(np.uint8)
            mask_bin = resize_if_needed(mask_bin, is_mask=True)

            stem = f"{study_id}_s{idx}"
            np.save(img_out / f"{stem}.npy", ct_norm)
            np.save(mask_out / f"{stem}.npy", mask_bin)
            saved += 1

    print(f"{split_name}: saved {saved} pairs from {len(pairs_by_study)} studies")
    return saved

n_train_mos = save_mosmed_pairs(train_studies, 'train')
n_val_mos = save_mosmed_pairs(val_studies, 'val')
n_test_mos = save_mosmed_pairs(test_studies, 'test')

assert n_train_mos + n_val_mos + n_test_mos == len(all_pairs), \
    "Saved count doesn't match expected -- something was dropped, re-run this cell."

mosmed_manifest = {
    'dataset': 'MosMedData',
    'target_size': TARGET_SIZE,
    'hu_window': [-1000, 400],
    'n_train': n_train_mos, 'n_val': n_val_mos, 'n_test': n_test_mos,
    'split_level': 'study/patient (no leakage across splits)',
}
with open(OUT / 'mosmed_manifest.json', 'w') as f:
    json.dump(mosmed_manifest, f, indent=2)

print("\nMosMedData manifest:", mosmed_manifest)

"""## Cell 8 - LIDC-IDRI: collect pairs, subsample to ~1000, patient-level split

Subsampled at the **patient** level to roughly match MosMedData's volume (LIDC-IDRI has ~9700
pairs across 578 patients if used in full — far more than MosMedData, which would badly skew
the hybrid set toward LIDC-IDRI's nodule-crop visual style).

"""

lidc_triples = []
for patient in sorted(os.listdir(seg_dir)):
    patient_path = seg_dir / patient
    if not patient_path.is_dir():
        continue
    for nod in sorted(os.listdir(patient_path)):
        nod_path = patient_path / nod
        for sl in sorted(os.listdir(nod_path)):
            sl_path = nod_path / sl
            img_path = sl_path / 'slice.png'
            mask_path = sl_path / 'MV05.png'
            if img_path.exists() and mask_path.exists():
                lidc_triples.append((img_path, mask_path, patient))

unique_patients = sorted(set(t[2] for t in lidc_triples))
print(f"Total LIDC-IDRI pairs available: {len(lidc_triples)} across {len(unique_patients)} patients")

pairs_by_patient = {}
for img_path, mask_path, patient in lidc_triples:
    pairs_by_patient.setdefault(patient, []).append((img_path, mask_path))

# Sort each patient's own pair list too -- without this, a patient's slices
# could still land in a different internal order between runs, which would
# change which pair gets index 0, 1, 2... in the saved filenames.
for patient in pairs_by_patient:
    pairs_by_patient[patient].sort(key=lambda pair: str(pair[0]))

random.seed(42)
shuffled_patients = unique_patients.copy()
random.shuffle(shuffled_patients)

TARGET_TOTAL = 1000
selected_patients = []
running_total = 0
for p in shuffled_patients:
    selected_patients.append(p)
    running_total += len(pairs_by_patient[p])
    if running_total >= TARGET_TOTAL:
        break

print(f"Selected {len(selected_patients)} patients, {running_total} pairs (subsampled)")

train_patients, temp_patients = train_test_split(selected_patients, test_size=0.4, random_state=42)
val_patients, test_patients = train_test_split(temp_patients, test_size=0.5, random_state=42)
print(f"Patient split: {len(train_patients)} train / {len(val_patients)} val / {len(test_patients)} test")

"""## Cell 9 — LIDC-IDRI: save train/val/test .npy pairs"""

def clear_old_lidc_files(split_name):
    """Remove any previously-saved LIDC_ files before writing this run's selection,
    so a changed patient selection never leaves old files behind."""
    img_dir = OUT / split_name / 'images'
    mask_dir = OUT / split_name / 'masks'
    removed = 0
    for f in os.listdir(img_dir):
        if f.startswith('LIDC_'):
            os.remove(img_dir / f)
            removed += 1
    for f in os.listdir(mask_dir):
        if f.startswith('LIDC_'):
            os.remove(mask_dir / f)
    return removed

def save_lidc_pairs(patient_list, split_name):
    removed = clear_old_lidc_files(split_name)
    if removed:
        print(f"{split_name}: cleared {removed} old LIDC-IDRI files before saving")

    img_out = OUT / split_name / 'images'
    mask_out = OUT / split_name / 'masks'
    saved = 0
    skipped = 0

    for patient in patient_list:
        for i, (img_path, mask_path) in enumerate(pairs_by_patient[patient]):
            img = load_lidc_image(img_path)
            mask = load_lidc_mask(mask_path)

            if img is None or mask is None:
                skipped += 1
                continue

            img_resized = resize_lidc(img, is_mask=False).astype(np.float32) / 255.0
            mask_resized = resize_lidc(mask, is_mask=True)
            mask_bin = (mask_resized > 127).astype(np.uint8)

            stem = f"LIDC_{patient}_{i}"
            np.save(img_out / f"{stem}.npy", img_resized)
            np.save(mask_out / f"{stem}.npy", mask_bin)
            saved += 1

    print(f"{split_name}: saved {saved} pairs from {len(patient_list)} patients (skipped {skipped})")
    return saved

n_train_lidc = save_lidc_pairs(train_patients, 'train')
n_val_lidc = save_lidc_pairs(val_patients, 'val')
n_test_lidc = save_lidc_pairs(test_patients, 'test')

lidc_manifest = {
    'dataset': 'LIDC-IDRI (nodule-crop, subsampled)',
    'target_size': TARGET_SIZE,
    'source_patients_available': len(unique_patients),
    'patients_selected': len(selected_patients),
    'n_train': n_train_lidc, 'n_val': n_val_lidc, 'n_test': n_test_lidc,
    'split_level': 'patient (no leakage across splits)',
    'note': 'images are nodule-centered crops (not full lung slices), resized to 512x512',
}
with open(OUT / 'lidc_manifest.json', 'w') as f:
    json.dump(lidc_manifest, f, indent=2)

print("\nLIDC-IDRI manifest:", lidc_manifest)

"""## Cell 10 — Final verification

Confirms both datasets are actually present on disk (not just "printed success" during a run
that may have silently lost writes to a dropped connection), and visualizes one sample from
each source pulled fresh from the saved files.

"""

print("=== Final counts on disk (ground truth check) ===")
combined_counts = {}
for split in ['train', 'val', 'test']:
    split_dir = OUT / split / 'images'
    files = os.listdir(split_dir)
    mos_count = sum(1 for f in files if f.startswith('study_'))
    lidc_count = sum(1 for f in files if f.startswith('LIDC_'))
    combined_counts[split] = {'mosmed': mos_count, 'lidc': lidc_count, 'total': len(files)}
    print(f"{split}: {len(files)} total  (MosMedData: {mos_count}, LIDC-IDRI: {lidc_count})")

expected_mos = {'train': n_train_mos, 'val': n_val_mos, 'test': n_test_mos}
expected_lidc = {'train': n_train_lidc, 'val': n_val_lidc, 'test': n_test_lidc}
all_ok = True
for split in ['train', 'val', 'test']:
    if combined_counts[split]['mosmed'] != expected_mos[split]:
        print(f"MISMATCH in {split}: expected {expected_mos[split]} MosMedData files, found {combined_counts[split]['mosmed']} -- re-run Cell 7.")
        all_ok = False
    if combined_counts[split]['lidc'] != expected_lidc[split]:
        print(f"MISMATCH in {split}: expected {expected_lidc[split]} LIDC-IDRI files, found {combined_counts[split]['lidc']} -- re-run Cell 9.")
        all_ok = False
if all_ok:
    print("\nAll counts match expected -- Phase 1 data is complete and verified.")

# Visual check: one sample from each source, loaded fresh from disk
train_img_dir = OUT / 'train' / 'images'
all_train_files = os.listdir(train_img_dir)
mosmed_sample = next((f for f in all_train_files if f.startswith('study_')), None)
lidc_sample = next((f for f in all_train_files if f.startswith('LIDC_')), None)

if mosmed_sample and lidc_sample:
    fig, axes = plt.subplots(2, 2, figsize=(10, 10))
    for row, fname in enumerate([mosmed_sample, lidc_sample]):
        img = np.load(train_img_dir / fname)
        mask = np.load(OUT / 'train' / 'masks' / fname)
        axes[row, 0].imshow(img, cmap='gray')
        axes[row, 0].set_title(fname)
        axes[row, 0].axis('off')
        axes[row, 1].imshow(img, cmap='gray')
        axes[row, 1].imshow(mask, cmap='Reds', alpha=0.4)
        axes[row, 1].set_title('with mask overlay')
        axes[row, 1].axis('off')
    plt.tight_layout()
    plt.show()

combined_manifest = {
    'target_size': TARGET_SIZE,
    'counts': combined_counts,
    'sources': [
        'MosMedData (Kaggle: mathurinache/mosmeddata-chest-ct-scans-with-covid19)',
        'LIDC-IDRI (Kaggle: shuyueg/lidc-idri-byslices, subsampled ~1000 pairs)',
    ],
}
with open(OUT / 'combined_manifest.json', 'w') as f:
    json.dump(combined_manifest, f, indent=2)

print("\nPhase 1 complete. Combined manifest saved to combined_manifest.json")

